version: "3.8"

services:
  # TiDB
  pd:
    image: pingcap/pd:v8.5.2
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - coupon-network

  tikv:
    image: pingcap/tikv:v8.5.2
    depends_on:
      - pd
    ports:
      - "20160:20160"
      - "20180:20180"
    volumes:
      - tikv-data:/var/lib/tikv
    networks:
      - coupon-network

  tidb:
    image: pingcap/tidb:v8.5.2
    depends_on:
      - tikv
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - tidb-data:/var/lib/tidb
    networks:
      - coupon-network

  # Redis Single Server (for single mode)
  redis-single:
    image: bitnami/redis:8.0.2
    ports:
      - "6379:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
      - "REDIS_PASSWORD=123456"
    volumes:
      - redis-single-data:/bitnami/redis/data
    networks:
      - coupon-network

  # Redis Cluster
  redis-node-1:
    image: bitnami/redis-cluster:8.0.2
    ports:
      - "7001:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
      - "REDIS_PASSWORD=123456"
      - "REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6"
      - "REDIS_CLUSTER_REPLICAS=1"
      - "REDIS_CLUSTER_CREATOR=yes"
    volumes:
      - redis-node-1-data:/bitnami/redis/data
    networks:
      - coupon-network

  redis-node-2:
    image: bitnami/redis-cluster:8.0.2
    ports:
      - "7002:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
      - "REDIS_PASSWORD=123456"
      - "REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6"
      - "REDIS_CLUSTER_REPLICAS=1"
    volumes:
      - redis-node-2-data:/bitnami/redis/data
    networks:
      - coupon-network

  redis-node-3:
    image: bitnami/redis-cluster:8.0.2
    ports:
      - "7003:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
      - "REDIS_PASSWORD=123456"
      - "REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6"
      - "REDIS_CLUSTER_REPLICAS=1"
    volumes:
      - redis-node-3-data:/bitnami/redis/data
    networks:
      - coupon-network

  redis-node-4:
    image: bitnami/redis-cluster:8.0.2
    ports:
      - "7004:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
      - "REDIS_PASSWORD=123456"
      - "REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6"
      - "REDIS_CLUSTER_REPLICAS=1"
    volumes:
      - redis-node-4-data:/bitnami/redis/data
    networks:
      - coupon-network

  redis-node-5:
    image: bitnami/redis-cluster:8.0.2
    ports:
      - "7005:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
      - "REDIS_PASSWORD=123456"
      - "REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6"
      - "REDIS_CLUSTER_REPLICAS=1"
    volumes:
      - redis-node-5-data:/bitnami/redis/data
    networks:
      - coupon-network

  redis-node-6:
    image: bitnami/redis-cluster:8.0.2
    ports:
      - "7006:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=no"
      - "REDIS_PASSWORD=123456"
      - "REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6"
      - "REDIS_CLUSTER_REPLICAS=1"
    volumes:
      - redis-node-6-data:/bitnami/redis/data
    networks:
      - coupon-network

  # Redis Exporter for monitoring
  redis-exporter:
    image: bitnami/redis-exporter:1.74.0
    ports:
      - "9121:9121"
    environment:
      - "REDIS_ADDR=redis://redis-node-1:6379"
      - "REDIS_USER="
      - "REDIS_PASSWORD=123456"
      - "REDIS_EXPORTER_LOG_LEVEL=info"
      - "REDIS_EXPORTER_CHECK_KEYS=*"
      - "REDIS_EXPORTER_CHECK_SINGLE_KEYS=coupon:*,rate_limit:*,lock:*"
      - "REDIS_EXPORTER_INCL_SYSTEM_METRICS=true"
      - "REDIS_EXPORTER_IS_CLUSTER=true"
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - coupon-network

  # Prometheus
  prometheus:
    image: prom/prometheus:v3.4.1
    ports:
      - "9090:9090"
    networks:
      - coupon-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  # Grafana
  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    networks:
      - coupon-network
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  tidb-data:
  tikv-data:
  redis-single-data:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:
  prometheus-data:
  grafana-data:

networks:
  coupon-network:
    driver: bridge
