version: "3.8"

services:
  # TiDB
  pd:
    image: pingcap/pd:v8.5.2
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - coupon-network

  tikv:
    image: pingcap/tikv:v8.5.2
    depends_on:
      - pd
    ports:
      - "20160:20160"
      - "20180:20180"
    volumes:
      - tikv-data:/var/lib/tikv
    networks:
      - coupon-network

  tidb:
    image: pingcap/tidb:v8.5.2
    depends_on:
      - tikv
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - tidb-data:/var/lib/tidb
    networks:
      - coupon-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - coupon-network

  # Prometheus
  prometheus:
    image: prom/prometheus:v3.4.1
    ports:
      - "9090:9090"
    networks:
      - coupon-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  # Grafana
  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    networks:
      - coupon-network
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  tidb-data:
  tikv-data:
  redis-data:
  prometheus-data:
  grafana-data:


networks:
  coupon-network:
    driver: bridge