spring:
  application:
    name: coupon-service
  profiles:
    active: dev
  #    active: prod

  # Config Spring Data JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Config Spring Actuator and Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  prometheus:
    metrics:
      export:
        enabled: true

# Default cache configuration
cache:
  redis:
    url: redis://localhost:6379
    password:
    min-idle: 5
    max-active: 20
    timeout: 3000
    retry-attempts: 3
    retry-interval: 1500
  memory:
    max-size: 1000
    enable-cleanup: true
    cleanup-interval: 300000
# Simple Rate Limiting (using Redis)
# No additional configuration needed
