spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://tidb/coupon-database?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Connection Pool Settings
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

# Cache configuration for production
cache:
  redis:
    # Mode: single or cluster
    mode: cluster
    password: 123456
    min-idle: 10
    max-active: 50
    timeout: 3000
    retry-attempts: 3
    retry-delay-min: 300
    retry-delay-max: 500
    reconnection-delay-min: 500
    reconnection-delay-max: 3000

    # Single server configuration for production
    single:
      address: redis://redis-single:6379
      connection-pool-size: 20
      connection-minimum-idle-size: 10

    # Cluster configuration for production
    cluster:
      nodes:
        - redis://redis-node-1:6379
        - redis://redis-node-2:6379
        - redis://redis-node-3:6379
        - redis://redis-node-4:6379
        - redis://redis-node-5:6379
        - redis://redis-node-6:6379
      scan-interval: 2000
      master-connection-pool-size: 20
      slave-connection-pool-size: 20
      read-mode: SLAVE
      subscription-mode: MASTER
