spring:
  application:
    name: coupon-service
  profiles:
    active: dev
  #    active: prod

  # Config Spring Data JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Config Spring Actuator and Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  prometheus:
    metrics:
      export:
        enabled: true

# Default cache configuration
cache:
  redis:
    cluster:
      nodes: redis://localhost:7001,redis://localhost:7002,redis://localhost:7003,redis://localhost:7004,redis://localhost:7005,redis://localhost:7006
      scan-interval: 2000
      master-connection-pool-size: 250
      slave-connection-pool-size: 250
      read-mode: SLAVE
      subscription-mode: MASTER
    password: ""
    min-idle: 5
    max-active: 20
    timeout: 3000
    retry-attempts: 3
    retry-delay-min: 300
    retry-delay-max: 500
    reconnection-delay-min: 500
    reconnection-delay-max: 3000
