spring:
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:4000/coupon-database?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Connection Pool Settings
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30

# Cache configuration for development
cache:
  redis:
    url: redis://localhost:6379
    password: ""


# Logging configuration
logging:
  level:
    org.redisson: DEBUG